language: generic
env:
  global:
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="devon4net"
    - REPO_DEST="devon4net.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - secure: XFCNzqav5dLQ/c2SVsZysKII6HurnP4hHVZcOgR4S9QHmbkkVik/kiJ/lFDNwcl+cMkhuY09shjJduFLnjpuBKVU+ph2skqyHzdmg0iS9F/9J4boXTQehN89OxmwqULCm+cDvV4LJ+NmvpuyC9/mB1t5YSFgxvNTT9DJBu/DJdVgf0Edl3rnbHz5IVaItiFcZq8DONHAys7CZTtbCqoo2RVsqYXaYw6wxy4FDufIIw+LTa8sZnuIruP2+26K9Jsuh+IhDPiDFs12bWCwjApkH342pndHT6JKWoiRwasH5doB7I1BFsmKsicI+PpaJuetOYJ550GsaZyOWbYUFc7OtP1arqIU/K/6+uCfIurWzuJPi0xahfWrb4S17/01fLlJOhtxmullbT9375sC7D/eSG6dtJiPyAvgRqAKq+TpQt+8EEPn1TNrnFO9ZuvywB520SKwGDyJ5auvNDw1k/Z3hUKsKV3pk60oGR5fhFf2E9l/eLFRAcjNfoMUBRBYY09VekbdTQv8OhU4Ofpy09YLfd1qEsHIYyTPju9/DLFAMIB0MmE9tig8R0y6eFjmX4Zx8Y3QuErPaLhCeD4YFyLk+39M9I0v0PSXj5BJQlaR4v1C7yTkFKRBnNuew0lg+B01SD+tfSCtqPnqOy2SS+0fC0Ya3omtNcaYohBybHwxFww=
stages:
  - name: Documentation
    if: (branch = develop) AND (type = push)
jobs:
  include:
    - stage: Documentation
      script:
        # Clone repositories
        - git clone -b develop --single-branch https://${GH_REPO_SOURCE}
        - git clone https://${GH_REPO_DEST}
        - git clone https://${GH_REPO_CONSOLIDATE}
        # Update wiki repository with documentation folder contents
        - yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
        - cd ${REPO_DEST}
        - grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
        # Terminate Travis CI build when no changes detected
        - |
          if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
            set +e 
            pkill -9 -P $$ &> /dev/null || true 
            exit 0
          else 
            git config user.email ${EMAIL}
            git config user.name ${USER}
            git status
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
            git push origin-wiki master
            cd ../${REPO_CONSOLIDATE}
            if [ ! -d ${REPO_DEST} ]; then git submodule add https://${GH_REPO_DEST}; fi;
            git submodule init
            git submodule update --recursive --remote
            cd ${REPO_DEST}
            git checkout master
            git pull
            cd ..
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
            git push origin-wiki master
          fi
