version: "3.8"
services:
  alejandria:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
volumes:
  postgres-volume: